### ISSUE TITLE
Improvement / Settings and Downloads / 1 minor issue

### ISSUE THREAD

**Issue by warhugger** [nullxception/boorusphere#14]
I'm loving the app so far, I only have a few enhancements that could prove useful for a lot of users.

Latest update added downloading the sample picture, it would be useful to have a setting to set a default action rather than prompt each time. For example I could set it to download large images always, or vice versa and for added benefit a long press could be used to open the prompt asking which to download.

A left handed mode that just shifts the lower user interface like downloads and info to the left. A long with this it would be really nice to change the amount of images loaded per 'page' or at least make reaching the final image start loading the next one as it's annoying to have to back out of a picture to keep scrolling.

Having options for download location and pathing might be useful. Like subfolders for at least sites or fancier would be the searched tag. Changing the download location might be a major benefit as it currently would fill main flash rather than the SD card. Don't know if that's possible with how android/Google has been lately 

*The minor issue is very simple, the left sidebar icon on the search bar has some of the search bar to the left of it. This makes clicking as a left handed person a bit annoying as I almost always miss the sidebar icon and hit that little area. It's not app breaking, but a bit annoying.

![Screenshot_20220730-064311-219](https://user-images.githubusercontent.com/52195109/181909375-108fd522-4284-4d0d-ae21-81b0f2ed3019.png)

I marked the are with blue.

Honestly have had a great experience with the app and love how simple it is.

**Comment by nullxception** [comment]
> Latest update added downloading the sample picture, it would be useful to have a setting to set a default action rather than prompt each time. For example I could set it to download large images always, or vice versa and for added benefit a long press could be used to open the prompt asking which to download.

Sorry actually it's intended, I decide to use download dialog because not only it gives us choices, but also :
- prevent accidental downloading
- avoid downloading weird original file, some content (such as animated ones) has zip/rar as original source instead of mp4/gif/webm.

Adding an option for that is easy, but that would just creating another problem like accidentally clicking download button, or not downloading the _right_ file (since it's subjective).
And yes, we can add a "confirm dialog" like on the browsers but that would be making another steps for users to _just_ download.

> A left handed mode that just shifts the lower user interface like downloads and info to the left.

What about in the center ? I'd prefer to not having so many options.

> A long with this it would be really nice to change the amount of images loaded per 'page' or at least make reaching the final image start loading the next one as it's annoying to have to back out of a picture to keep scrolling.

nice idea, I can add that option.
for auto-load-more on preview page, I'm not sure if it's possible, but I'll try.

> Having options for download location and pathing might be useful. Like subfolders for at least sites or fancier would be the searched tag. Changing the download location might be a major benefit as it currently would fill main flash rather than the SD card. Don't know if that's possible with how android/Google has been lately

I'd like to, but it's already a pain enough to just save a file in /sdcard/Download/ folder, so I'm not going to add it.

> *The minor issue is very simple, the left sidebar icon on the search bar has some of the search bar to the left of it. This makes clicking as a left handed person a bit annoying as I almost always miss the sidebar icon and hit that little area. It's not app breaking, but a bit annoying.

You don't have to click sidebar icon, just swipe from left-to-right in the screen.

[Preview](https://user-images.githubusercontent.com/58150791/181919772-4a0ff8ef-a195-4f19-93fd-7f05df6ab90c.webm)
