### ISSUE TITLE
[Feature request] Add a way to come back after starting a search through a tag 

### ISSUE THREAD

**Issue by Palloxin** [nullxception/boorusphere#47]
https://user-images.githubusercontent.com/75091899/207057501-947607e2-d6ba-4ef1-b4d0-4366b67ad06c.mp4

after starting a search through the results of the first search (a tag of a single post of the first search), i would like to come back to the post where the second search started. If i was not clear enough just ask me questions.

**Comment by Palloxin** [comment]
I would say that this feature is very important and, if implemented, would mean an huge improvement in the QoL of the user

**Comment by nullxception** [comment]
Sorry, with current app architecture, it's impossible to mimick the behaviour of web browser.

**Comment by Palloxin** [comment]
It is really a pity then

**Comment by Palloxin** [comment]
This might be a breaking point for some users pushing them to other apps that do that thing instead. well, if you don't plan to earn from the app ,praticing your coding skills or just hobby then it is fine

**Comment by nullxception** [comment]
> This might be a breaking point for some users pushing them to other apps that do that thing instead. well, if you don't plan to earn from the app ,praticing your coding skills or just hobby then it is fine

Sorry, it just I'm not interested to implement multi back stack entry because it requires a lot of data flow redesign, not to mention about performance consideration since user can have literally thousands of content scrolled in back stack being held in memory.

This also applied to things like tabs feature (just in case someone thinks about that).
