### ISSUE TITLE
[Feature Request] A way to stop the download of a gif or video

### ISSUE THREAD

**Issue by Palloxin** [nullxception/boorusphere#55]
![IMG_20221212_161647](https://user-images.githubusercontent.com/75091899/207082312-63218dec-b30c-48a4-8a44-f95cc4d23036.jpg)
Sometimes files are too big and the user might change his idea and continue scrolling instead of waiting the download of the gif/video and prevent the internet connection to be slow for no reason. Another reason might be that the user has a slow internet connection and clogging it (download in background) with the download of a gif/video that he might have clicked by mistake is uncomfortable.
You could add in the settings some option to make downloads of gif and videos automatic, manual or manual if the file exceed x amount of bytes

**Comment by nullxception** [comment]
on extended_image package, there's `cancelToken` option, but apparently it only for canceling pending network request.
so when request is already performed and image widget is already fetching the image at certain percentage, `cancelToken` become useless due to nature of `Future` on dart which cannot be stopped midway.
CancelableOperation also doesn't make this issues closed because it only interject subscription to the actual `Future`.

[dart-lang/sdk/issues/42855](https://github.com/dart-lang/sdk/issues/42855) 
[async/CancelableOperation](https://api.flutter.dev/flutter/async/CancelableOperation/CancelableOperation.fromFuture.html)
