### ISSUE TITLE
[Features Request] Improve already exist features and suggestions for new features

### ISSUE THREAD

**Issue by Nonanne** [nullxception/boorusphere#63]
**Improve**
> - sort Artists, Characters, Copyright, Metadata and etc. out of normal tags (or change color text different _Ex. Character tags - green text_) edited: I see it's only including in some sites only. (not sort in gelbooru)
> - add 'All' in Favorites page to show all fav media in one page

**Suggestions**
> - add option to backup settings (including server saved)
> - add 'Saved Tags' to show fav tags (for fast search when you want to search your fav tags)
> - add 'meta tags' in searching such as score, id, rating
> - add 'Saved Pages' for following pages (when you want to roll back to previous search with one-click _Ex. search tag1 tag2 tag3 sort:score with one-click_)
> - show 'score' in details media page

**Comment by nullxception** [comment]
> > * sort Artists, Characters, Copyright, Metadata and etc. out of normal tags (or change color text different _Ex. Character tags - green text_) edited: I see it's only including in some sites only. (not sort in gelbooru)
There's nothing we can do about this since only handful select of booru API supports categorized tags.

> > * add 'All' in Favorites page to show all fav media in one page
Added to consideration.

> > * add option to backup settings (including server saved)
Duplicated: #41
Also already fixed on : 80b0980e620df9004f9bcbccca7e7ea106da703c (will be present in the next update)

> > * add 'Saved Tags' to show fav tags (for fast search when you want to search your fav tags)
Isn't that what search history is already doing ?

> > * add 'meta tags' in searching such as score, id, rating
- rating selection does make sense to be added as part of search screen (instead of settings safe mode), added to consideration.
- id is already short enough to type, doesn't really make sense.
- score is not supported by all booru APIs.

> > * add 'Saved Pages' for following pages (when you want to roll back to previous search with one-click _Ex. search tag1 tag2 tag3 sort:score with one-click_)
This doesn't make any sense to me, there's no "pages" in this app, just endless scrolling like a social media app. so there's nothing to be "saved". 

> > * show 'score' in details media page
Added to consideration, note that only handful select of booru API support this.

**Comment by nullxception** [comment]
> Bugs: when press '+' in suggested search it doesn't remove typing word _Ex. typing "back" then press 'background' in suggested search. then result is 'back background'_

Thanks, I'll add this bug to a new issues to track since it's not good to shovel multiple issues into one.

**Comment by nullxception** [comment]
> > Bugs: when press '+' in suggested search it doesn't remove typing word _Ex. typing "back" then press 'background' in suggested search. then result is 'back background'_
> 
> Thanks, I'll add this bug to a new issues to track since it's not good to shovel multiple issues into one.

Tracked on https://github.com/nullxception/boorusphere/issues/64

**Comment by nullxception** [comment]
Since single issues that has multiple suggestions are hard to track, I made follow-up issues (on #87, #88) to make tracking easier.
So this one will be closed instead.
