### ISSUE TITLE
Bug: laggy search suggestions

### ISSUE THREAD

**Issue by HotarunIchijou** [nullxception/boorusphere#95]
### Type

Booru parser issues

### Bug description

Sometimes it return 'null' and suggestions are different from gelbooru one, for example, in order

### Steps to reproduce

For example:
1. Select gelbooru and start typing "Hatsune_miku"
2. It returns 'null'

### Android version

Android 13

### App version

Boorusphere v1.3.1

### Additional context

Also suggestions updating delay are too big

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nullxception** [comment]
It's has different result and slow because we fetch multiple URLs: getting a suggestion based on a character typed at beginning, middle, and at end of the word. 3 URLs at the same time.

Booru sites are dumb, and you have to do that just to anticipate what people want to search, whether the typed character is at the beginning, middle, or it's at the end of the word.

**Comment by nullxception** [comment]
but now that you mention it, I think it's better to just pass the typed characters and let the server suggest. might breaks suggestion on some server that doesn't support wildcard query, but atleast it's faster.
